# Generated by Django 5.1.7 on 2025-03-15 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PayerGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='payer group name', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='payer name', max_length=255, unique=True)),
                ('payer_group', models.ForeignKey(help_text='payer group', on_delete=django.db.models.deletion.CASCADE, related_name='payers', to='payer.payergroups')),
            ],
        ),
        migrations.CreateModel(
            name='PayerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the payer as it appears in the document.', max_length=255)),
                ('payer_number', models.CharField(blank=True, help_text='The payer number as it appears in the document.', max_length=50, null=True)),
                ('tax_id', models.CharField(blank=True, help_text='The tax ID of the payer as it appears in the document.', max_length=50, null=True)),
                ('payer', models.ForeignKey(help_text='The payer this detail belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='payer.payers')),
            ],
            options={
                'unique_together': {('name', 'payer_number', 'tax_id')},
            },
        ),
    ]
